
# Default output file for Terraform plan
variables:
  ENV: development
  OWNER: dso
  OWNER_EMAIL: aws-dso@securitycompass.com
  ENV_FILE: dev.tfvars

cache:
  paths:
    - .terraform

stages:
  - validate
  - build
  - deploy

validate:
  image: 757687274468.dkr.ecr.us-east-1.amazonaws.com/aws-dso
  stage: validate
  tags:
    - docker-aws
  script:
    - terraform validate -var-file=$ENV_FILE -var 'environment=$ENV' -var 'owner=$OWNER' -var 'owner_email=$OWNER_EMAIL'

plan:
  image: 757687274468.dkr.ecr.us-east-1.amazonaws.com/aws-dso
  stage: build
  tags:
    - docker-aws
  script:
    - terraform plan -var-file=$ENV_FILE -var 'environment=$ENV' -var 'owner=$OWNER' -var 'owner_email=$OWNER_EMAIL'
  artifacts:
    name: plan
    paths:
      - $PLAN

    
# Separate apply job for manual launching Terraform as it can be destructive
# action.
apply:
  image: 757687274468.dkr.ecr.us-east-1.amazonaws.com/aws-dso
  tags:
    - docker-aws
  stage: deploy
  environment:
    name: $ENV
  script:
    - terraform apply -var-file=$ENV_FILE -var 'environment=$ENV' -var 'owner=$OWNER' -var 'owner_email=$OWNER_EMAIL' -input=false
  dependencies:
    - plan
  when: manual

